#!/usr/bin/env python3
"""Generated golden info for testing.

This file is auto-generated by generate_golden_files_and_data.py.
"""

GOLDEN_INFO = {
  "txt": {
    "path": "/Users/wylie/Desktop/Projects/MakeItParquet/tests/files_for_testing_with/sample_files/sample.txt",
    "stat_obj": {
      "st_mode": 33188,
      "st_ino": 75214777,
      "st_dev": 16777232,
      "st_nlink": 1,
      "st_uid": 501,
      "st_gid": 20,
      "st_size": 226669,
      "st_atime": 1741261271.389705,
      "st_mtime": 1741261271.2237623,
      "st_ctime": 1741261271.224531
    },
    "file_name": "sample.txt",
    "file_size": 226669,
    "file_extension": ".txt",
    "file_or_directory": "file"
  },
  "csv": {
    "path": "/Users/wylie/Desktop/Projects/MakeItParquet/tests/files_for_testing_with/sample_files/sample.csv",
    "stat_obj": {
      "st_mode": 33188,
      "st_ino": 75214775,
      "st_dev": 16777232,
      "st_nlink": 1,
      "st_uid": 501,
      "st_gid": 20,
      "st_size": 22,
      "st_atime": 1741261271.3661718,
      "st_mtime": 1741261271.2201374,
      "st_ctime": 1741261271.2208407
    },
    "file_name": "sample.csv",
    "file_size": 22,
    "file_extension": ".csv",
    "file_or_directory": "file"
  },
  "tsv": {
    "path": "/Users/wylie/Desktop/Projects/MakeItParquet/tests/files_for_testing_with/sample_files/sample.tsv",
    "stat_obj": {
      "st_mode": 33188,
      "st_ino": 75214776,
      "st_dev": 16777232,
      "st_nlink": 1,
      "st_uid": 501,
      "st_gid": 20,
      "st_size": 1288,
      "st_atime": 1741261271.3850145,
      "st_mtime": 1741261271.2214105,
      "st_ctime": 1741261271.2218242
    },
    "file_name": "sample.tsv",
    "file_size": 1288,
    "file_extension": ".tsv",
    "file_or_directory": "file"
  },
  "parquet": {
    "path": "/Users/wylie/Desktop/Projects/MakeItParquet/tests/files_for_testing_with/sample_files/sample.parquet",
    "stat_obj": {
      "st_mode": 33188,
      "st_ino": 75214778,
      "st_dev": 16777232,
      "st_nlink": 1,
      "st_uid": 501,
      "st_gid": 20,
      "st_size": 132101,
      "st_atime": 1741261271.224825,
      "st_mtime": 1741261271.226972,
      "st_ctime": 1741261271.227387
    },
    "file_name": "sample.parquet",
    "file_size": 132101,
    "file_extension": ".parquet",
    "file_or_directory": "file"
  },
  "json": {
    "path": "/Users/wylie/Desktop/Projects/MakeItParquet/tests/files_for_testing_with/sample_files/sample.json",
    "stat_obj": {
      "st_mode": 33188,
      "st_ino": 75214808,
      "st_dev": 16777232,
      "st_nlink": 1,
      "st_uid": 501,
      "st_gid": 20,
      "st_size": 46,
      "st_atime": 1741261271.6692634,
      "st_mtime": 1741261271.6701167,
      "st_ctime": 1741261271.6730275
    },
    "file_name": "sample.json",
    "file_size": 46,
    "file_extension": ".json",
    "file_or_directory": "file"
  },
  "xlsx": {
    "path": "/Users/wylie/Desktop/Projects/MakeItParquet/tests/files_for_testing_with/sample_files/sample.xlsx",
    "stat_obj": {
      "st_mode": 33188,
      "st_ino": 75214809,
      "st_dev": 16777232,
      "st_nlink": 1,
      "st_uid": 501,
      "st_gid": 20,
      "st_size": 4099,
      "st_atime": 1741261271.6743052,
      "st_mtime": 1741261271.6792288,
      "st_ctime": 1741261271.6792288
    },
    "file_name": "sample.xlsx",
    "file_size": 4099,
    "file_extension": ".xlsx",
    "file_or_directory": "file"
  },
  "directory": {
    "path": "/Users/wylie/Desktop/Projects/MakeItParquet/tests/files_for_testing_with/sample_files",
    "stat_obj": {
      "st_mode": 16877,
      "st_ino": 67260383,
      "st_dev": 16777232,
      "st_nlink": 8,
      "st_uid": 501,
      "st_gid": 20,
      "st_size": 256,
      "st_atime": 1739737743.179124,
      "st_mtime": 1741261271.6789606,
      "st_ctime": 1741261271.6789606
    },
    "file_name": "sample_files",
    "file_size": 256,
    "file_extension": "",
    "file_or_directory": "directory"
  }
}
